$install_docker_script = <<SCRIPT
echo "Installing Docker..."
curl -sSL https://get.docker.com | sh
usermod -aG docker vagrant
SCRIPT

$manager_script = <<SCRIPT
echo Swarm Init
docker swarm init --listen-addr 10.100.199.200:2377 --advertise-addr 10.100.199.200:2377
docker swarm join-token --quiet worker > /vagrant/worker_token
SCRIPT

$worker_script = <<SCRIPT
echo Swarm join
docker swarm join --token $(cat /vagrant/worker_token) 10.100.199.200:2377
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_check_update = true
  config.vm.synced_folder ".", "/vagrant"
  config.vm.provision "shell", inline: $install_docker_script, privileged: true
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.define :manager, primary: true do |manager|
    manager.vm.network "private_network", ip: "10.100.199.200"
    manager.vm.hostname = "manager"
    manager.vm.provision "shell", inline: $manager_script, privileged: true
    manager.vm.provision "reload"
  end

  (1..2).each do |i|
    config.vm.define "worker0#{i}" do |worker|
      worker.vm.network "private_network", ip: "10.100.199.20#{i}"
      worker.vm.hostname = "worker0#{i}"
      worker.vm.provision "shell", inline: $worker_script, privileged: true   
      worker.vm.provision "reload"
    end
  end
end
